# Generated by Django 5.1.4 on 2025-01-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsApp', '0002_alter_utilisateur_telephone_budget_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10),
        ),
    ]
